apiVersion: apps/v2
kind: Deployment
metadata:
  name: blue-deployment
  spec :
   replies: 2
   selector :
   match labels :
      name : docker-spring-boot
   template:
   metadata :
   labels :
    name : blue-deployment
   spec :
   containers :
   - name : blue-deployment
     image : nareshbabu1991/docker-spring-boot
     ports :
     - name : http
       continer port : 8080 
       protocal : TCP 
---
apiVersion : v1
kind : service
 metadata :
   name : blue-deployment 
 labels : 
  name :docker-spring-boot
  spec : 
  - port : 80 
  target port : http
  protocol : TCP 
 selector : blue-deployment 
 type : node port
