apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-spring-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-spring-boot
  template:
    metadata:
      labels:
        app: docker-spring-boot
    spec:
      containers:
        - name: spring-boot
          image: nareshbabu1991/docker-spring-boot : blue
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-spring-boot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: docker-spring-boot
