apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-spring-boot
spec:
  selector:
    matchLabels:
      app: docker-spring-boot
  replicas: 2 
  template: 
    metadata:
      labels:
        app: docker-spring-boot
    spec:
      containers:
      - name: docker-spring-boot
        image: nareshbabu1991/docker-spring-boot-4.0.0-2
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: docker-spring-boot
spec:
  type: LoadBalancer
  selector:
    app: docker-spring-boot
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
